### ISSUE TITLE
[UI] CAFECA landing page 主視覺 Demo

### ISSUE THREAD

**Issue by JodieWu** [CAFECA-IO/cafeca#153]
依據找到的兩版風格分別出兩版Landing page 主視覺的部分 Demo

**Comment by JodieWu** [comment]
完成時間： 4 hr

V1:
https://xd.adobe.com/view/20933650-1ccf-40fd-870f-05bffc0f5634-75c0/?fullscreen&hints=off

V2:
https://xd.adobe.com/view/f3fb8f33-b826-4528-97d7-05c5b7afb8b5-a6a8/?fullscreen&hints=off

**Comment by Luphia** [comment]
採用 v2 版本
