### ISSUE TITLE
[UI] Web-Partner

### ISSUE THREAD

**Issue by JodieWu** [CAFECA-IO/cafeca#165]
在網頁中放置與我們有合作關係之夥伴 Logo 展示

**Comment by JodieWu** [comment]
完成時間：1 hr
https://xd.adobe.com/view/f3fb8f33-b826-4528-97d7-05c5b7afb8b5-a6a8/?fullscreen&hints=off

**Comment by Luphia** [comment]
- Partner 需全數展開陳列於網頁

**Comment by JodieWu** [comment]
修改時間：0.5 hr
https://xd.adobe.com/view/f3fb8f33-b826-4528-97d7-05c5b7afb8b5-a6a8/?fullscreen&hints=off
