### ISSUE TITLE
[UI][LandingPage]Features UI & Function & RWD

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/cafeca#2]
- rwd 
  - destop
<img width="1338" alt="Screen Shot 2022-03-07 at 4 49 29 PM" src="https://user-images.githubusercontent.com/17249354/156998216-104b838f-a4e1-44e8-aab1-9e271514a9cd.png">
  - mobile
<img width="1055" alt="Screen Shot 2022-03-07 at 4 49 44 PM" src="https://user-images.githubusercontent.com/17249354/156998278-75123d13-077d-4809-b65f-633bda379702.png">

**Comment by TzuHanLiang** [comment]
take 5hrs

**Comment by Luphia** [comment]
- image background #39
