### ISSUE TITLE
[Graphic Design][靈感發想與構圖]

### ISSUE THREAD

**Issue by Luphia** [CAFECA-IO/cafeca#23]
當我們生活在地球上，每天看著月亮的陰晴圓缺，甚至還有專門賞月的節日。
而到了月球上，「賞地球」是不是也會變成了一件非常有閒情逸致的事呢？

本週主題: 賞地球

**Comment by JodieWu** [comment]
完成時間：3hr
![image](https://user-images.githubusercontent.com/98379087/160358419-c8f60ba1-3e65-48a4-a369-dedb3929a3eb.jpg)

Emotional Map：
Fascinating and relaxed
