### ISSUE TITLE
[UI][LandingPage] Main UI & RWD

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/cafeca#3]
<img width="1343" alt="Screen Shot 2022-03-07 at 4 51 35 PM" src="https://user-images.githubusercontent.com/17249354/156998539-b6dbddc6-eeca-46b2-91ba-2748da5653e1.png">

**Comment by TzuHanLiang** [comment]
take 3hrs, 多個 image 疊加的 rwd花了一點時間調整

**Comment by Luphia** [comment]
- background image #38 
- animation #36
