### ISSUE TITLE
[UI][LandingPage] Datas UI & RWD

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/cafeca#6]
<img width="941" alt="Screen Shot 2022-03-11 at 4 10 29 PM" src="https://user-images.githubusercontent.com/17249354/157827999-a82635cf-4205-4b72-913f-7b0895017546.png">
<img width="529" alt="Screen Shot 2022-03-11 at 4 10 55 PM" src="https://user-images.githubusercontent.com/17249354/157828066-f81df838-2776-4a98-8c3b-eca2bb5aa6ea.png">

**Comment by TzuHanLiang** [comment]
take 3hrs

**Comment by Luphia** [comment]
- animation #36
