### ISSUE TITLE
[BUG] image blend mode

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/cafeca#65]
在 landing page 裡面的 Features 5張圖片檔 及 products page 裡面的3張圖片檔 與背景的 blend mode 沒有處理好，造成圖片有陰影，目前不確定圖片檔改成 svg 並且用 img tag 處理而不是做為 div background 是否可以解決這個問題，或是要再想新的解決方案，或是跟設計師要新的圖片檔。

**Comment by TzuHanLiang** [comment]
take 1.5hrs 採取上述措施未達到預期效果。有與設計師溝通，希望設計師提供新的圖片檔再與以嘗試。

**Comment by Luphia** [comment]
- replace with CAFECA Official 2.0
