### ISSUE TITLE
[UI][LandingPage] contast us -- Form

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/cafeca#7]
UI & RWD

<img width="1011" alt="Screen Shot 2022-03-11 at 4 12 29 PM" src="https://user-images.githubusercontent.com/17249354/157828289-48a1a827-1145-475d-b4f1-789f9661b917.png">

<img width="529" alt="Screen Shot 2022-03-11 at 4 12 10 PM" src="https://user-images.githubusercontent.com/17249354/157828238-52442f7c-3ff0-4528-b76d-421714ad0473.png">

**Comment by TzuHanLiang** [comment]
take 4hrs

**Comment by Luphia** [comment]
- animation #36
- background #38 
- textarea background #40
