### ISSUE TITLE
[UI][LandingPage] Footer

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/cafeca#8]
- rwd
<img width="1351" alt="Screen Shot 2022-03-07 at 5 06 02 PM" src="https://user-images.githubusercontent.com/17249354/157000780-7b5b1b6d-31c0-49a1-bb31-740b8dc9e41d.png">

<img width="1024" alt="Screen Shot 2022-03-07 at 5 05 21 PM" src="https://user-images.githubusercontent.com/17249354/157000684-b8cc47c4-e91a-459b-8b24-bfb51f88470c.png">

**Comment by TzuHanLiang** [comment]
take 2.5hrs （0.5hrs 微調）

**Comment by Luphia** [comment]
- backgound #38
