### ISSUE TITLE
[UI] 玉山頁面微調

### ISSUE THREAD

**Issue by JodieWu** [CAFECA-IO/cafeca#81]
微調玉山Landing page 按鈕、視覺引導、FAQ 配色、Android 按鈕名稱

**Comment by JodieWu** [comment]
完成時間：4 hr
https://xd.adobe.com/view/c1af7e4d-aafd-4bf4-bf67-6875ff1c9c2c-94fc/?fullscreen

**Comment by Luphia** [comment]
需補上
- FAQ 展開
- copyright

**Comment by JodieWu** [comment]
完成時間：0.5 hr
https://xd.adobe.com/view/c1af7e4d-aafd-4bf4-bf67-6875ff1c9c2c-94fc/?fullscreen
