### ISSUE TITLE
[CIS Design] CAFECA Business card 調整

### ISSUE THREAD

**Issue by JodieWu** [CAFECA-IO/cafeca#82]
調整名片正面、簡化背面資訊、新增其他人的名片

**Comment by JodieWu** [comment]
完成時間：1 hr
https://drive.google.com/file/d/1SxId45dG1U2NJb7K-pJN_-LJmlikRswZ/view?usp=sharing

**Comment by Luphia** [comment]
需補上
- 燙銀圖檔
- 亮膜圖檔

**Comment by JodieWu** [comment]
完成時間：0.5 hr
https://drive.google.com/drive/folders/1FLM3MuI6HKWSipEhuMh_PqFeWbLr5zFo?usp=sharing
