### ISSUE TITLE
[Feature] 多語系 & 合作夥伴更新

### ISSUE THREAD

**Issue by TzuHanLiang** [CAFECA-IO/cafeca#86]
- 根據設計稿，新增英文語系
- 更新合作夥伴

**Comment by TzuHanLiang** [comment]
- take 3hrs
- 設計稿中的 [Privacy ](https://xd.adobe.com/view/110da88c-3f51-4168-9e40-d5b288bde070-445e/screen/91857c14-6d28-4426-9422-c7f1a564d498/specs/)是中文版的(待設計師修改）
- 手機size的英文版 products 頁面動畫有跑位
- 中英文切換 data 6300 vs 63 不會即時更換

**Comment by Luphia** [comment]
- privacy policy #100
