### ISSUE TITLE
[7 oz. Cafe] Logo Design

### ISSUE THREAD

**Issue by JodieWu** [CAFECA-IO/cafeca#98]
以Logo概念發想＋配色進行 logo 設計

**Comment by Luphia** [comment]
Logo 色系：普魯士藍 + 玫瑰金

**Comment by JodieWu** [comment]
完成時間：5 HR
https://drive.google.com/drive/folders/1505r_siPBwRpijfToCDQrG-ezsoQog2x?usp=sharing
